
#Environment Variable
app:
   fixedRate: ${FTP_CLIENT_RATE:60000}
   ftp:
      hostname: ${FTP_HOST:localhost}
      port: ${FTP_PORT:2121}
      username: ${FTP_USERNAME:universalbank}
      password: ${FTP_PASSWORD:universalbank}
      